package Ventana;
import ConstValues.Names;
import javax.swing.table.*;


public class Principal extends javax.swing.JFrame{
    DefaultTableModel table;
    int columnas = 0;
    double totalqzFnum = 0;
    double totalPlagionum = 0;
    double totalFeldnum =0;
    double totalSuma = 0;
    static double totalqzFnumNorm = 0; 
    static double totalPlagionumNorm = 0;
    static double totalFeldnumNorm = 0;
    static int Tipo = 0;
    static int MinQF = 0;
    String mat[][]={}; 
    String cabeza[]={"Qz / Feldespatoide"," Feldespato", "Plagioclasa", "Total"};
    

            
    public Principal() {
       initComponents();
       table = new DefaultTableModel(mat, cabeza);
       jTabla.setModel(table);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QzFGrup = new javax.swing.ButtonGroup();
        IntruExtruGrup = new javax.swing.ButtonGroup();
        General = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        btGuardar = new javax.swing.JButton();
        txtFeldValue = new javax.swing.JLabel();
        TituloQzF = new javax.swing.JLabel();
        QzF = new javax.swing.JLabel();
        TituloTipo1 = new javax.swing.JLabel();
        txtPlagValue = new javax.swing.JLabel();
        txtQzFvalue = new javax.swing.JTextField();
        txtPlagio = new javax.swing.JTextField();
        txtFeld = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        btClasificar = new javax.swing.JButton();
        jProgreso = new javax.swing.JProgressBar();
        chkQz = new javax.swing.JCheckBox();
        chkFeldois = new javax.swing.JCheckBox();
        chkIntru = new javax.swing.JCheckBox();
        chkExtru = new javax.swing.JCheckBox();
        txtTotalQz = new javax.swing.JLabel();
        txtTituloTotalPlagio = new javax.swing.JLabel();
        txtTituloTotalQzNorm = new javax.swing.JLabel();
        txtTituloTotalFeldesp = new javax.swing.JLabel();
        txtTotalFeldesp = new javax.swing.JLabel();
        txtTotalPlagio = new javax.swing.JLabel();
        txtTituloTotalQz = new javax.swing.JLabel();
        txtTotalQzNorm = new javax.swing.JLabel();
        txtTituloTotalQzNorm1 = new javax.swing.JLabel();
        txtTituloTotalQzNorm2 = new javax.swing.JLabel();
        txtTotalPlagioNorm = new javax.swing.JLabel();
        txtTotalFeldespNorm = new javax.swing.JLabel();
        txtRoca = new javax.swing.JLabel();
        btCleanAll = new javax.swing.JButton();
        btCleanLast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCRI 1.0");
        setFocusTraversalPolicyProvider(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        General.setFocusTraversalPolicyProvider(true);
        General.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Clasificación de Rocas Ígneas");
        General.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 361, -1));

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        General.add(btGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 80, 30));

        txtFeldValue.setText("Feldespato:");
        General.add(txtFeldValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 90, 30));

        TituloQzF.setText("Mineral Escencial Principal: ");
        General.add(TituloQzF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 20));

        QzF.setText("Cuarzo: ");
        QzF.setAlignmentX(0.5F);
        General.add(QzF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        TituloTipo1.setText("Tipo de Roca: ");
        General.add(TituloTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, 20));

        txtPlagValue.setText("Plagioclasa:");
        txtPlagValue.setToolTipText("");
        General.add(txtPlagValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 120, 30));

        txtQzFvalue.setText("0");
        txtQzFvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQzFvalueActionPerformed(evt);
            }
        });
        General.add(txtQzFvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 50, 30));

        txtPlagio.setText("0");
        General.add(txtPlagio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 50, 30));

        txtFeld.setText("0");
        General.add(txtFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 50, 30));

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabla);

        General.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 700, 110));

        btClasificar.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        btClasificar.setText("Clasificar");
        btClasificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClasificarActionPerformed(evt);
            }
        });
        General.add(btClasificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 110, 40));

        jProgreso.setMaximum(5);
        jProgreso.setToolTipText("");
        jProgreso.setStringPainted(true);
        General.add(jProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, 20));

        QzFGrup.add(chkQz);
        chkQz.setText("Cuarzo");
        chkQz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkQzActionPerformed(evt);
            }
        });
        General.add(chkQz, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 80, 30));

        QzFGrup.add(chkFeldois);
        chkFeldois.setText("Fledespatoides");
        chkFeldois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFeldoisActionPerformed(evt);
            }
        });
        General.add(chkFeldois, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 30));

        IntruExtruGrup.add(chkIntru);
        chkIntru.setText("Intrusiva");
        chkIntru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIntruActionPerformed(evt);
            }
        });
        General.add(chkIntru, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 81, -1, 30));

        IntruExtruGrup.add(chkExtru);
        chkExtru.setText("Extrusiva");
        chkExtru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkExtruActionPerformed(evt);
            }
        });
        General.add(chkExtru, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 81, -1, 30));

        txtTotalQz.setText("0.0");
        General.add(txtTotalQz, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 40, 20));

        txtTituloTotalPlagio.setText("Promedio: ");
        General.add(txtTituloTotalPlagio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 70, 20));

        txtTituloTotalQzNorm.setText("Normalizado:");
        General.add(txtTituloTotalQzNorm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 100, 20));

        txtTituloTotalFeldesp.setText("Promedio: ");
        General.add(txtTituloTotalFeldesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 70, 20));

        txtTotalFeldesp.setText("0.0");
        General.add(txtTotalFeldesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 40, 20));

        txtTotalPlagio.setText("0.0");
        General.add(txtTotalPlagio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 40, 20));

        txtTituloTotalQz.setText("Promedio:");
        txtTituloTotalQz.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        General.add(txtTituloTotalQz, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 70, 20));

        txtTotalQzNorm.setText("0.0");
        General.add(txtTotalQzNorm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 40, 20));

        txtTituloTotalQzNorm1.setText("Normalizado:");
        General.add(txtTituloTotalQzNorm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, 20));

        txtTituloTotalQzNorm2.setText("Normalizado:");
        General.add(txtTituloTotalQzNorm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 100, 20));

        txtTotalPlagioNorm.setText("0.0");
        General.add(txtTotalPlagioNorm, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 40, 20));

        txtTotalFeldespNorm.setText("0.0");
        General.add(txtTotalFeldespNorm, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 40, 20));

        txtRoca.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtRoca.setForeground(new java.awt.Color(159, 34, 34));
        txtRoca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRoca.setText("---");
        General.add(txtRoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 580, 20));

        btCleanAll.setText("Borrar Todo");
        btCleanAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCleanAllActionPerformed(evt);
            }
        });
        General.add(btCleanAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 110, 30));

        btCleanLast.setText("Borrar Ultimo");
        btCleanLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCleanLastActionPerformed(evt);
            }
        });
        General.add(btCleanLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 110, 30));

        getContentPane().add(General, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 750, 460));
        General.getAccessibleContext().setAccessibleName("Programa para clasificación de Rx Ígneas");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
String qzF = txtQzFvalue.getText();
int qzFnum = Integer.parseInt(qzF);
totalqzFnum += qzFnum;
String Plagioclasa = txtPlagio.getText();
int Plagionum = Integer.parseInt(Plagioclasa);
totalPlagionum += Plagionum;
String Feldespato = txtFeld.getText();
int Feldnum = Integer.parseInt(Feldespato);
totalFeldnum += Feldnum;
int Suma = qzFnum + Plagionum + Feldnum;
totalSuma += Suma;
String Total = Integer.toString(Suma);


String datos[] = {qzF, Plagioclasa, Feldespato, Total};


if(qzFnum == 0 && Plagionum == 0 &&  Feldnum == 0){
    if(this.columnas <5){       
           table.addRow(datos);
           this.columnas += 1;
           jProgreso.setValue(this.columnas);
    }       
          return;
}
if(this.columnas <5){
    table.addRow(datos);
    this.columnas += 1;
    jProgreso.setValue(this.columnas);
    totalqzFnumNorm = (totalqzFnum*100)/totalSuma;
    totalPlagionumNorm = (totalPlagionum*100)/totalSuma;
    totalFeldnumNorm = (totalFeldnum*100)/totalSuma;
    txtTotalQz.setText(String.valueOf(totalqzFnum/this.columnas));
    txtTotalFeldesp.setText(String.valueOf(totalFeldnum/this.columnas));
    txtTotalPlagio.setText(String.valueOf(totalPlagionum/this.columnas));
    txtTotalQzNorm.setText(String.valueOf(totalqzFnumNorm));
    txtTotalPlagioNorm.setText(String.valueOf(totalPlagionumNorm));
    txtTotalFeldespNorm.setText(String.valueOf(totalFeldnumNorm));

}
    }//GEN-LAST:event_btGuardarActionPerformed

    private void chkQzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkQzActionPerformed
        this.QzF.setText("Cuarzo:");
        MinQF = 1;
    }//GEN-LAST:event_chkQzActionPerformed

    private void chkFeldoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFeldoisActionPerformed
        this.QzF.setText("Feldespatoide:");
        MinQF = 2;
    }//GEN-LAST:event_chkFeldoisActionPerformed

    private void btClasificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClasificarActionPerformed
        if(MinQF == 0){
            txtRoca.setText(Names.errormin);            
        }
        if(Tipo == 0){
            txtRoca.setText(Names.errortipo);            
        }
        if(Tipo == 1 && MinQF==1){
          String Roca = Intrusivas.ClasificacionQzI.getRock(totalqzFnumNorm, totalFeldnumNorm, totalPlagionumNorm);
        txtRoca.setText(Roca);  
        }
        if(Tipo == 1 && MinQF==2){
          String Roca = Intrusivas.ClasificacionFI.getRock(totalqzFnumNorm, totalFeldnumNorm, totalPlagionumNorm);
        txtRoca.setText(Roca);  
        }
        if(Tipo == 2 && MinQF==1){
          String Roca = Extrusivas.ClasificacionQzE.getRock(totalqzFnumNorm, totalFeldnumNorm, totalPlagionumNorm);
        txtRoca.setText(Roca);  
        }
        if(Tipo == 2 && MinQF==2){
          String Roca = Extrusivas.ClasificacionFE.getRock(totalqzFnumNorm, totalFeldnumNorm, totalPlagionumNorm);
        txtRoca.setText(Roca);  
        }
        
    }//GEN-LAST:event_btClasificarActionPerformed

    private void chkIntruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIntruActionPerformed
       Tipo = 1;
    }//GEN-LAST:event_chkIntruActionPerformed

    private void chkExtruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkExtruActionPerformed
       Tipo = 2;
    }//GEN-LAST:event_chkExtruActionPerformed

    private void txtQzFvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQzFvalueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQzFvalueActionPerformed

    private void btCleanAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCleanAllActionPerformed
      for(int i=0; i<this.columnas; i++){
        table.removeRow(0);
      }
    this.columnas = 0;
    jProgreso.setValue(0);
    totalqzFnumNorm = 0; 
    totalPlagionumNorm = 0;
    totalFeldnumNorm = 0;
    totalqzFnum = 0;
    totalPlagionum = 0;
    totalFeldnum =0;
    totalSuma = 0;
    
    txtTotalQz.setText(String.valueOf(0.0));
    txtTotalFeldesp.setText(String.valueOf(0.0));
    txtTotalPlagio.setText(String.valueOf(0.0));
    txtTotalQzNorm.setText(String.valueOf(0.0));
    txtTotalPlagioNorm.setText(String.valueOf(0.0));
    txtTotalFeldespNorm.setText(String.valueOf(0.0));
    }//GEN-LAST:event_btCleanAllActionPerformed

    private void btCleanLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCleanLastActionPerformed
        if(this.columnas == 0){
            jProgreso.setValue(0);
            totalqzFnumNorm = 0; 
            totalPlagionumNorm = 0;
            totalFeldnumNorm = 0;
            totalqzFnum = 0;
            totalPlagionum = 0;
            totalFeldnum =0;
            totalSuma = 0;
            return;
        }
        if(this.columnas == 1){
            jProgreso.setValue(0);
            totalqzFnumNorm = 0; 
            totalPlagionumNorm = 0;
            totalFeldnumNorm = 0;
            totalqzFnum = 0;
            totalPlagionum = 0;
            totalFeldnum =0;
            totalSuma = 0;
            txtTotalQz.setText(String.valueOf(totalqzFnum));
            txtTotalFeldesp.setText(String.valueOf(totalFeldnum));
            txtTotalPlagio.setText(String.valueOf(totalPlagionum));
            txtTotalQzNorm.setText(String.valueOf(totalqzFnumNorm));
            txtTotalPlagioNorm.setText(String.valueOf(totalPlagionumNorm));
            txtTotalFeldespNorm.setText(String.valueOf(totalFeldnumNorm));
            this.columnas -= 1;
            table.removeRow(this.columnas);
            jProgreso.setValue(this.columnas);
          return;
        }
        
        
        
        
        
        this.columnas -= 1;
        table.removeRow(this.columnas);
        jProgreso.setValue(this.columnas);
        
               
  
    }//GEN-LAST:event_btCleanLastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel General;
    private javax.swing.ButtonGroup IntruExtruGrup;
    private javax.swing.JLabel QzF;
    private javax.swing.ButtonGroup QzFGrup;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloQzF;
    private javax.swing.JLabel TituloTipo1;
    private javax.swing.JButton btClasificar;
    private javax.swing.JButton btCleanAll;
    private javax.swing.JButton btCleanLast;
    private javax.swing.JButton btGuardar;
    private javax.swing.JCheckBox chkExtru;
    private javax.swing.JCheckBox chkFeldois;
    private javax.swing.JCheckBox chkIntru;
    private javax.swing.JCheckBox chkQz;
    private javax.swing.JProgressBar jProgreso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    private javax.swing.JTextField txtFeld;
    private javax.swing.JLabel txtFeldValue;
    private javax.swing.JLabel txtPlagValue;
    private javax.swing.JTextField txtPlagio;
    private javax.swing.JTextField txtQzFvalue;
    private javax.swing.JLabel txtRoca;
    private javax.swing.JLabel txtTituloTotalFeldesp;
    private javax.swing.JLabel txtTituloTotalPlagio;
    private javax.swing.JLabel txtTituloTotalQz;
    private javax.swing.JLabel txtTituloTotalQzNorm;
    private javax.swing.JLabel txtTituloTotalQzNorm1;
    private javax.swing.JLabel txtTituloTotalQzNorm2;
    private javax.swing.JLabel txtTotalFeldesp;
    private javax.swing.JLabel txtTotalFeldespNorm;
    private javax.swing.JLabel txtTotalPlagio;
    private javax.swing.JLabel txtTotalPlagioNorm;
    private javax.swing.JLabel txtTotalQz;
    private javax.swing.JLabel txtTotalQzNorm;
    // End of variables declaration//GEN-END:variables

   

}

